# Generated by Django 6.0 on 2026-02-04 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gonderen', models.CharField(max_length=100)),
                ('icerik', models.TextField(blank=True, null=True)),
                ('dosya', models.FileField(blank=True, null=True, upload_to='chat_dosyalari/')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
