# Generated by Django 6.0 on 2026-02-04 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_sayfa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesaj',
            name='oda',
            field=models.CharField(default='genel', max_length=50),
            preserve_default=False,
        ),
    ]
