# Generated by Django 6.0 on 2026-03-29 17:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_sayfa', '0002_mesaj_oda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesaj',
            name='oda',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='Danisan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(blank=True, max_length=20, null=True)),
                ('tc_no', models.CharField(blank=True, max_length=11, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Uzman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=150)),
                ('unvan', models.CharField(max_length=150)),
                ('brans', models.CharField(choices=[('diyetisyen', 'Diyetisyen'), ('psikolog', 'Psikolog'), ('fizyoterapi', 'Fizyoterapi')], max_length=50)),
                ('resim_emoji', models.CharField(default='👨\u200d⚕️', max_length=10)),
                ('biyografi', models.TextField()),
                ('ucret', models.DecimalField(decimal_places=2, default=1250.0, max_digits=10)),
                ('puan', models.FloatField(default=5.0)),
                ('aktif_mi', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Randevu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField()),
                ('saat', models.TimeField()),
                ('durum', models.CharField(choices=[('beklemede', 'Onay Bekliyor'), ('onaylandi', 'Onaylandı'), ('tamamlandi', 'Tamamlandı'), ('iptal', 'İptal Edildi')], default='onaylandi', max_length=20)),
                ('odeme_alindi', models.BooleanField(default=False)),
                ('danisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gecmis_randevular', to='ana_sayfa.danisan')),
                ('uzman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='randevu_listesi', to='ana_sayfa.uzman')),
            ],
        ),
    ]
