# Generated by Django 6.0 on 2026-03-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_sayfa', '0003_alter_mesaj_oda_danisan_uzman_randevu'),
    ]

    operations = [
        migrations.AddField(
            model_name='danisan',
            name='profil_resmi',
            field=models.ImageField(blank=True, null=True, upload_to='profiller/'),
        ),
        migrations.AddField(
            model_name='uzman',
            name='profil_resmi',
            field=models.ImageField(blank=True, null=True, upload_to='profiller/'),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='durum',
            field=models.CharField(default='onaylandi', max_length=20),
        ),
    ]
