# Generated by Django 6.0 on 2026-03-30 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_sayfa', '0004_danisan_profil_resmi_uzman_profil_resmi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musaitlik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gun', models.DateField()),
                ('saat', models.TimeField()),
                ('dolu_mu', models.BooleanField(default=False)),
                ('uzman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saatleri', to='ana_sayfa.uzman')),
            ],
        ),
    ]
