# Generated by Django 6.0 on 2026-03-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_sayfa', '0005_musaitlik'),
    ]

    operations = [
        migrations.AddField(
            model_name='danisan',
            name='bakiye',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='randevu',
            name='alinan_ucret',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='durum',
            field=models.CharField(choices=[('beklemede', 'Onay Bekliyor'), ('onaylandi', 'Onaylandı'), ('reddedildi', 'Reddedildi / İade Edildi')], default='beklemede', max_length=20),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='odeme_alindi',
            field=models.BooleanField(default=True),
        ),
    ]
