# Generated by Django 6.0 on 2026-03-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_sayfa', '0006_danisan_bakiye_randevu_alinan_ucret_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uzman',
            name='bakiye',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
