# Generated by Django 6.0 on 2026-03-30 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_sayfa', '0007_uzman_bakiye'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yorum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puan', models.IntegerField(default=5)),
                ('icerik', models.TextField()),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('danisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ana_sayfa.danisan')),
                ('uzman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yorumlar', to='ana_sayfa.uzman')),
            ],
        ),
    ]
