# Generated by Django 6.0 on 2026-03-30 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ana_sayfa', '0008_yorum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mesaj',
            name='dosya',
        ),
        migrations.AddField(
            model_name='mesaj',
            name='okundu',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='mesaj',
            name='gonderen',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mesaj',
            name='icerik',
            field=models.TextField(default='Eski Mesaj'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mesaj',
            name='oda',
            field=models.CharField(max_length=255),
        ),
    ]
